### ISSUE TITLE
inspec2ckl does not read the --metadata as JSON

### ISSUE THREAD

**Issue by b-mad** [mitre/inspec_tools#212]
Within PluginCLI, the read of the metadata file does not convert from JSON to a Hash. As a result all conversion downstream are not able to properly set attributes in the generated checklist when executing `inspec2ckl --metadata file`

Note the implementation here:

https://github.com/mitre/inspec_tools/blob/2862786fedefec4d488106bba8a9b580b95c74a6/lib/inspec_tools/plugin_cli.rb#L120-L125

**Comment by TMVUONG-HI** [comment]
Sorry about asking a beginner's (Inspec/Ruby) question here because I don't where to pose it - how do I set up Inspec_Tools on a Windows machine (running inspec-4.50.3.1-x64 and rubyinstaller-3.0.3-1-x64.exe)?  I have recently started to use the [Powershell script](https://github.com/vmware/dod-compliance-and-automation/blob/master/vsphere/6.7/vsphere/powercli/VMware_vSphere_6.7_STIG_ESXi_Inspec_Runner.ps1), but can't seem to get the call to inspec_tools command to work.

            $cklCommand = {inspec_tools inspec2ckl -j $reportFile -o $cklFile}
            Invoke-Command -ScriptBlock $cklCommand
